### PR TITLE
add url to the release in the supplementary material

### PR DESCRIPTION
**Pull request by eeholmes**
This addresses issue #13

### CODE REVIEW

**Comment by eeholmes** [comment]
With this pull request the link to supplementary material now points to the current release. Example from my testing.

image

**Comment by vsoch** [comment]
This is a great idea! But let's make this still a variable that the user provides. The reason is because they might use the action on a non-release event, or want a different URL used.

**Comment by vsoch** [comment]
And it should still be optional, meaning the default for html url is set to None and then in the action python script we check if it is defined, and only set it if that's the case. Otherwise folks using the action now will get different behavior.

**Comment by eeholmes** [comment]
Got it. Where would they define the html_url? Updating the workflow every time a release is made seems non ideal. Perhaps defining an option like
```
html_url: release_url
```
And if html_url == "release_url" then that url is used?

But default is None so behavior doesn't change?

**Comment by vsoch** [comment]
- The html url would be another variable for the action
- Then in the example (that does a release) you can show that specific metadata from GitHub for them to use.
- The action.yml would check if it's defined before adding to the script as a flag
- The python variable in the script would check if it's defined before adding to the metadata

**Comment by eeholmes** [comment]
Closing this pull request since I merged in your changes.

**Pull request closed without merging**
